services:
  web:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:8.1-fpm
    volumes:
      - ./:/code