openapi: 3.0.0
info:
  title: 'gorest API'
  description: 'Free REST API service'
  version: '2.0'
paths:
  '/public/v2/users/{id}':
    get:
      summary: 'get list of users'
      operationId: getListOfUsers
      parameters:
        -
          name: user-id
          in: path
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: 'Bad request'
        '404':
          description: 'Requested resource not found'
        '405':
          description: 'Method not allowed'
        '429':
          description: 'Too many requests'
        '500':
          description: 'Internal server error'
      security:
        -
          securityScheme: bearerAuth
          type: http
          scheme: bearer
    delete:
      summary: 'delete user'
      operationId: deleteUser
      parameters:
        -
          name: user-id
          in: path
          required: true
      responses:
        '200':
          description: OK
        '201':
          description: 'A resource was successfully created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Authentication failed'
        '404':
          description: 'Requested resource not found'
        '405':
          description: 'Method not allowed'
        '422':
          description: 'Data validation failed'
        '429':
          description: 'Too many requests'
        '500':
          description: 'Internal server error'
      security:
        -
          securityScheme: bearerAuth
          type: http
          scheme: bearer
    patch:
      summary: 'delete user'
      operationId: patchUser
      parameters:
        -
          parameter: user-id
          name: user-id
          in: path
          required: true
      responses:
        '200':
          description: OK
        '201':
          description: 'A resource was successfully created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Authentication failed'
        '404':
          description: 'Requested resource not found'
        '405':
          description: 'Method not allowed'
        '422':
          description: 'Data validation failed'
        '429':
          description: 'Too many requests'
        '500':
          description: 'Internal server error'
      security:
        -
          securityScheme: bearerAuth
          type: http
          scheme: bearer
  /public/v2/users:
    post:
      summary: 'create new user'
      operationId: createUser
      responses:
        '200':
          description: OK
        '201':
          description: 'A resource was successfully created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Authentication failed'
        '404':
          description: 'Requested resource not found'
        '405':
          description: 'Method not allowed'
        '422':
          description: 'Data validation failed'
        '429':
          description: 'Too many requests'
        '500':
          description: 'Internal server error'
      security:
        -
          securityScheme: bearerAuth
          type: http
          scheme: bearer
