FROM php:8.1-fpm-alpine as app
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/
RUN set -eux; \
    install-php-extensions pdo pdo_mysql;
ENV COMPOSER_ALLOW_SUPERUSER=1
COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer
COPY ./composer.* ./
RUN composer install
COPY ./ .
RUN composer dump-autoload --optimize
RUN chown -R 1000:1000 ./core/view
FROM app as app_dev
ENV XDEBUG_MODE=off
COPY ./docker/php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
RUN set -eux; \
    install-php-extensions xdebug;
