services:
  nginx:
    image: nginx:1.23
    ports:
      - "8080:80"
    volumes:
      - ../:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - ../:/code
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/zz-docker-php-ext-xdebug.ini
      - ./php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  mysql:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: UsersDatabase
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - 3306:3306