FROM composer:latest AS composer
FROM node:latest AS npm
FROM php:8.1-fpm
COPY --from=composer usr/bin/composer /usr/bin/composer
COPY --from=npm usr/bin/npm /usr/bin/npm
RUN pecl install xdebug \
&& docker-php-ext-enable xdebug \
&& docker-php-ext-install pdo pdo_mysql
RUN adduser phpcomposeruser
USER phpcomposeruser
RUN whoami
RUN id
WORKDIR  /code