FROM composer:latest AS composer
FROM php:8.1-fpm
COPY --from=composer usr/bin/composer /usr/bin/composer
RUN pecl install xdebug \
&& docker-php-ext-enable xdebug \
&& docker-php-ext-install pdo pdo_mysql
RUN adduser phpcomposeruser
USER phpcomposeruser
RUN whoami
RUN id
WORKDIR  /code