services:
  web:
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#      - ../:/var/www/html
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.fpm
    env_file: .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${DB_PORT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
  mysql:
    image: mariadb:latest
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

volumes:
  mysqldata: